# Generated by Django 3.2.8 on 2021-10-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse', models.CharField(max_length=5000, verbose_name='verse')),
                ('highlighted_word', models.CharField(max_length=30, verbose_name='highlighted word')),
                ('answers', models.ManyToManyField(related_name='answers', related_query_name='answers', to='search.Verses')),
            ],
        ),
    ]
