# Generated by Django 3.2.8 on 2021-10-20 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mofrdatWaJmo3', '0002_ques_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
    ]
