# Generated by Django 3.2.8 on 2021-10-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mofrdatWaJmo3', '0003_ques_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ques',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
