# Generated by Django 3.2.8 on 2021-10-20 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mofrdatWaJmo3', '0004_alter_ques_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ques',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
    ]
